---
title: "step6"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source('C:/Users/yangs/Desktop/2017 autunm/statistical computing/assignment-2-yangslmn/source script.R')
```

# This is the code I made

```{r code}

trueA <- 5
trueB <- 0
trueSd <- 10
sampleSize <- 31

# create independent x-values 
x <- (-(sampleSize-1)/2):((sampleSize-1)/2)
# create dependent values according to ax + b + N(0,sd)... similar to linear regression model
y <-  trueA * x + trueB + rnorm(n=sampleSize,mean=0,sd=trueSd) #vector y

plot(x,y, main="Test Data")


# Example: plot the likelihood profile of the slope a

slopelikelihoods <- lapply(seq(3, 7, by=.05), slopevalues ) # apply the slopevalues function to each list.
plot (seq(3, 7, by=.05), slopelikelihoods , type="l", xlab = "values of slope parameter a", ylab = "Log likelihood")
```
```{r}

compare_outcomes<-function(iterations)
{outputmatrix<-array(dim=c(2,10))
burnIn<-iterations *0.5
for (i in 1:10)
{  startvalue_random<-c(runif(1,0,5), rnorm(1, 0,8), runif(1,0,20))
chain<-run_metropolis_MCMC(startvalue_random, iterations)
outputmatrix[1,i]<-mean(chain[-(1: burnIn),][,1])
outputmatrix[2,i]<-sd(chain[-(1:burnIn),][,1])

}
return(outputmatrix)
}

graph_function<- function(chain, burnIn)
{ par(mfrow = c(2,3))
  alphabet<-c('a','b','sd')
  true<-c(trueA, trueB, trueSd)
  for(i in 1:3)
  {
    hist(chain[-(1:burnIn), i], nclass=30, main=paste("Posterior of",alphabet[i]),xlab="True value = red line")
    abline(v=mean(chain[-(1:burnIn), i]))
    abline(v= true[i], col='red')}
  for(j in 1:3)
  { plot(chain[-(1: burnIn), j], type = 'l', xlab = 'True value=red line',main = paste('Chain value of',alphabet[j]))
    abline(h=true[j], col='red')}
  
}

compare_outcomes(1000)

```

#compare_outcomes
```{r}
compare_outcomes(1000)
compare_outcomes(10000)
compare_outcomes(100000)

#We can find that the difference between each loops decreases when the iteration increases.
# So the accuracy increases as we set large iteration.

```

